### ISSUE TITLE
Can't run Xcode 7.3.1 

### ISSUE THREAD

**Issue by Apofeozzz** [mshibanami/DefaultMarginDisabler#5]
Xcode quit unexpectedly while using the DefaultMarginDisabler plug-in.

**Comment by mshibanami** [comment]
Hi @Apofeozzz.
Thanks for reporting that problem. I didn't realized that.😓

Could you explain details about it?
How do you know DefaultMarginDisabler caused it?
When did Xcode die?
Does it continue that problem  if you reinstall DefaultMrginDisabler?
Do you have some crash logs?

You can also debug this plugin. Download the source code, open `DefaultMarginDisabler.xcodeproj` file, then you can just run it.
I think It's pretty easy to trace it because this is a very small plugin.
Ah, but if you want to debug it, you should set your Xcode 7.3.1 as Excecutable like this:
![skitched-20161103-013605](https://cloud.githubusercontent.com/assets/1333214/19937772/e4ff43ac-a165-11e6-8f7b-dd2ec030cd90.jpg)

**Comment by mshibanami** [comment]
This repo is no longer supported. See more details here:
https://github.com/mshibanami/DefaultMarginDisabler/issues/6#issuecomment-284203844
